import { TskCustomerForm } from "@/components/orders/customer/tsk-customer.form";

const customsTariffs = [
	{
		id: 1,
		name: "Misceláneas (ropa, calzado, alimentos, etc.)",
		fee: 10,
		fee_type: "WEIGHT",
		chapter: "CAPÍTULO 9 - MISCELEÁNEAS",
	},
	{
		id: 2,
		name: "Ventiladores",
		fee: 25,

		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 3,
		name: "Aires acondicionados",
		fee: 60,

		max_quantity: 2,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 4,
		name: "Calentadores eléctricos",
		fee: 40,

		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 5,
		name: "Lámparas y lámparas halógenas",
		fee: 30,

		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 6,
		name: "Bombillos y focos LED",
		fee: 2,

		max_quantity: 20,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 7,
		name: "Cables eléctricos",
		fee: 15,

		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},
	{
		id: 8,
		name: "Interruptores y enchufes",
		fee: 5,
		max_quantity: 10,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 1 - APARATOS ELÉCTRICOS",
	},

	{
		id: 9,
		name: "Cámaras fotográficas",
		fee: 60,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},
	{
		id: 10,
		name: "Cámaras de vídeo",
		fee: 100,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},
	{
		id: 11,
		name: "Proyectores (Data show) y similares",
		fee: 100,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},
	{
		id: 12,
		name: "Partes, piezas y accesorios fotográficos",
		fee: 100,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},
	{
		id: 13,
		name: "Papel fotográfico",
		fee: 3,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},
	{
		id: 14,
		name: "Papel para impresos",
		fee: 15,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 2 - APARATOS FOTOGRÁFICOS Y SIMILARES",
	},

	{
		id: 15,
		name: "Pinturas y barnices",
		fee: 4,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 16,
		name: "Diluentes",
		fee: 4,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 17,
		name: "Lámparas eléctricas",
		fee: 20,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 18,
		name: "Linternas",
		fee: 3,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 19,
		name: "Tanques de agua",
		fee: 60,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 20,
		name: "Mangueras",
		fee: 5,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 21,
		name: "Escaleras domésticas",
		fee: 30,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},
	{
		id: 22,
		name: "Alarmas contra intrusos",
		fee: 60,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 3 - PINTURAS Y OTROS",
	},

	{
		id: 23,
		name: "Sillas",
		fee: 20,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 4 - MUEBLES Y OTROS",
	},
	{
		id: 24,
		name: "Mesas",
		fee: 40,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 4 - MUEBLES Y OTROS",
	},
	{
		id: 25,
		name: "Estanterías",
		fee: 50,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 4 - MUEBLES Y OTROS",
	},
	{
		id: 26,
		name: "Armarios",
		fee: 60,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 4 - MUEBLES Y OTROS",
	},

	{
		id: 27,
		name: "Camisas",
		fee: 10,
		max_quantity: 10,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 5 - ROPA Y CALZADO",
	},
	{
		id: 28,
		name: "Pantalones",
		fee: 10,
		max_quantity: 10,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 5 - ROPA Y CALZADO",
	},
	{
		id: 29,
		name: "Zapatos",
		fee: 15,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 5 - ROPA Y CALZADO",
	},
	{
		id: 30,
		name: "Calzado deportivo",
		fee: 20,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 5 - ROPA Y CALZADO",
	},

	{
		id: 31,
		name: "Alimentos procesados",
		fee: 10,
		fee_type: "WEIGHT",
		chapter: "CAPÍTULO 6 - ALIMENTOS Y OTROS",
	}, // por peso
	{
		id: 32,
		name: "Bebidas alcohólicas",
		fee: 20,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 6 - ALIMENTOS Y OTROS",
	},
	{
		id: 33,
		name: "Frutas y verduras",
		fee: 5,
		fee_type: "WEIGHT",
		chapter: "CAPÍTULO 6 - ALIMENTOS Y OTROS",
	},

	{
		id: 34,
		name: "Computadoras portátiles",
		fee: 150,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 7 - EQUIPOS DE COMPUTO",
	},
	{
		id: 35,
		name: "Tablets",
		fee: 100,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 7 - EQUIPOS DE COMPUTO",
	},
	{
		id: 36,
		name: "Accesorios (mouse, teclado)",
		fee: 30,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 7 - EQUIPOS DE COMPUTO",
	},

	{
		id: 37,
		name: "Ciclomotores eléctricos de hasta dos plazas",
		fee: 200,
		max_quantity: 2,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},

	{
		id: 38,
		name: "Baterías de litio",
		fee: 60,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 39,
		name: "Otras baterías",
		fee: 35,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 40,
		name: "Carburador",
		fee: 40,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 41,
		name: "Delco (distribuidor)",
		fee: 30,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 42,
		name: "Guardafangos",
		fee: 40,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 43,
		name: "Parabrisas",
		fee: 150,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 44,
		name: "Neumáticos para autos ligeros",
		fee: 60,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 45,
		name: "Neumáticos para autos pesados",
		fee: 100,
		max_quantity: 7,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 46,
		name: "Neumáticos para motos o ciclomotores",
		fee: 35,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 47,
		name: "Cámaras para neumáticos de autos ligeros",
		fee: 10,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},
	{
		id: 48,
		name: "Cámaras para neumáticos de autos pesados",
		fee: 30,
		max_quantity: 5,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 8 - ACCESORIOS Y REPUESTOS PARA VEHÍCULOS",
	},

	{
		id: 49,
		name: "Televisores",
		fee: 100,
		max_quantity: 2,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 10 - ELECTRÓNICOS",
	},
	{
		id: 50,
		name: "Reproductores de DVD",
		fee: 40,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 10 - ELECTRÓNICOS",
	},
	{
		id: 51,
		name: "Consolas de videojuegos",
		fee: 60,
		max_quantity: 2,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 10 - ELECTRÓNICOS",
	},

	{
		id: 52,
		name: "Taladros eléctricos",
		fee: 50,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 11 - HERRAMIENTAS",
	},
	{
		id: 53,
		name: "Sierras eléctricas",
		fee: 60,
		max_quantity: 2,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 11 - HERRAMIENTAS",
	},
	{
		id: 54,
		name: "Lijadoras",
		fee: 40,
		max_quantity: 3,
		fee_type: "UNIT",
		chapter: "CAPÍTULO 11 - HERRAMIENTAS",
	},
];

export const ZustandPage = () => {
	return (
		<div>
			<TskCustomerForm />
		</div>
	);
};
